/*
Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair of element from the array.
Note: AND is bitwise '&' operator.

Input:
The first line of the input contains a single integer T, denoting the number of test cases. Then T test cases follow. Each test-case has two lines of the input, the first line contains an integer denoting the size of an array N and the second line of input contains N positive integers

Output:
For each testcase, print Maximum AND Value of a pair in a separate line.

User Task:
The task is to complete the function maxAND() which takes the array elements and N (size of array) and input and returns the maximum AND value generated by any pair in the array.

Constraints:
1 <=T <= 100
1 <= N <= 100
1 <= arr[i] <= 104

Example:
Input:
2
4
4 8 12 16
4
4 8 16 2

Output:
8
0

Explanation:
Testcase 1: Pair (8,12) has the Maximum AND Value  i.e. 8.
Testcase 2: Maximum AND Value is 0.

#########################################################Solution#######################################################################
*/

class AND{
    public static int checkBit(int pattern,int[] arr,int n){
        int count=0;
        for(int i=0;i<n;i++){
            if((pattern & arr[i])==pattern)
                count++;
        }
        
        return count;
    }
    public static int maxAND (int arr[], int n) {
        int count=0;
        int res=0;
        for(int bit=31;bit>=0;bit--){
            count=checkBit(res|(1<<bit),arr,n);
        
        if(count>=2)
            res|=(1<<bit);
        }
        
        return res;
    }
    
}
